<MyTwoLineAvatarIconListItem>
    text: "COM1"
    secondary_text: "Description"
    on_release: root.view.on_port_select(self.text)
    IconLeftWidgetWithoutTouch:
        icon: "usb-port"


<MyListItemWithCheckbox>
    checkbox_name: "Example 1"
    padding: dp(15)
    adaptive_height: True
    divider: None
    _no_ripple_effect: True
    MyRightCheckboxContainer:
        id: checkbox_container
        # on_state: app.session.set_param(root.checkbox_name, bool(self.active))