# <MainMobileView>
#     orientation: "vertical"
#     MDTopAppBar:
#         id: top_app_bar
#         title: "Robonomik Communicator"
#     MDTabs:
#         lock_swiping: True
#         on_tab_switch: root.on_tab_switch(*args)
#         MyTab:
#             title: "Connect"
#             ConnectMobileSubview:
#         MyTab:
#             title: "Settings"
#             SettingsMobileSubview:


# <ConnectMobileSubview>


# <SettingsMobileSubview>